### PR TITLE
New docker themes added

### PR DESCRIPTION
**Pull request by AniqJaved**

### CODE REVIEW

**Comment by loopDelicious** [comment]
If you update row 26 of App.tsx to the `latest` tag instead of `0.0.1`, does the docker command still error?

I don't see the theme has cascaded, and it's only in dark mode now.

**Comment by loopDelicious** [comment]
@AniqJaved I just saw the video in the other PR. Since you define the classes as `.theme-docker-dark` and `.theme-docker-light`, can you check that you've updated `setTheme()` properly? I don't see light mode takes effect when updating in my docker desktop settings.

**Comment by AniqJaved** [comment]
https://user-images.githubusercontent.com/86469982/197690112-1475b80c-2b57-4009-abd5-e5046ba51d98.mp4

**Comment by AniqJaved** [comment]
@loopDelicious I had made a commit🚀 on my forked repository. Kindly check that.

**Comment by AniqJaved** [comment]
@loopDelicious i have made some commits in my forked repository. Kindly check that

**Pull request merged**
